### ISSUE TITLE
rpcapi is bound to 0.0.0.0:8547 by default. Why is this needed?

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/sf-ethereum#1]
When starting mindreader, it forks off geth like this:

`/usr/bin/bsc-geth --networkid=56 --datadir=/var/lib/geth --ipcpath=/var/lib/dfuse/sf/ipc --port=30305 --rpc --rpcapi=admin,debug,eth,net,web3 --rpcport=8547 --rpcaddr=0.0.0.0 --rpcvhosts=* --nousb --firehose-deep-mind`

Why is it listening on 0.0.0.0:8547 for admin requests by default?  Seems insecure?

**Comment by sduchesneau** [comment]
Good point, I will remove admin and debug from rpc whitelist

**Comment by sduchesneau** [comment]
8547 instead of regular 8545 is simply so mindreader listens by default to a different port than a "miner" node or just a "peering" node.
