### ISSUE TITLE
Indexing: Handle LogAddressIndex queries via an IndexProvider

### ISSUE THREAD

**Issue by froch** [streamingfast/sf-ethereum#18]
We want to be able to find and serve LogAddressIndex indexes

---
Acceptance Criteria:
- [x] create a `LogAddressIndexProvider` conforming to the `bstream.IndexProvider` interface
- [x] determine if a given block number is within an index
- [x] determine if a given block number matches an element in an index
- [x] fetch and return all next matching indexes for a given block number

**Comment by froch** [comment]
Whiteboard of the flow for querying an IndexProvider

![image (1)](https://user-images.githubusercontent.com/70759/152603727-ba72cf8c-187b-48ad-90f6-1c6ae44c2c49.png)

**Comment by sduchesneau** [comment]
bstream branch stepd/index-provider contains the (almost-complete) code for querying the logAddressIndex from the IrrIndexProvider...
names will have to be reworked in that last one to prevent confusion.
