### ISSUE TITLE
Initialize LogAddressIndexProvider from the Transform

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/sf-ethereum#20]
* BasicLogFilter (implementing interface Transform)  should implement a new method, ~GetIndexProvider() that will utlimately be called from the firehose (returns the provider, or nil if anything goes wrong)
* in cmd/sfeth/cli/firehose.go, when registering the BasicLogFilterFactory, it should be pre-loaded (using a FactoryFactory :tm: ) with the index store and the indexSizes array.

* in bstream and maybe the firehose package, you need to check if GetIndexProvider is implemented via a new interface, and call it on your transforms (see the transformReg.BuildFromTransforms method, that generates a preprocessor, now you need the same mechanism to generate an index)
* What to do if more than one tranform generates an index ? panic for now..... or maybe just use one of them.

**Comment by froch** [comment]
<img width="837" alt="Screen Shot 2022-02-09 at 10 25 27 AM" src="https://user-images.githubusercontent.com/70759/153232663-06037ab6-76a7-46c1-a8ef-edc441513fb0.png">

**Comment by sduchesneau** [comment]
@froch the https://github.com/streamingfast/streamingfast-client (command `sf eth ...`) can run a request against a local firehose with transforms.
