### ISSUE TITLE
Default command line uses obsolete arguments to geth

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/sf-ethereum#6]
```
(mindreader-node) WARN [11-26|15:17:46.583] The flag --rpc is deprecated and will be removed June 2021, please use --http  (log_plugin/to_zap_log_plugin.go:131)
(mindreader-node) WARN [11-26|15:17:46.583] The flag --rpcaddr is deprecated and will be removed June 2021, please use --http.addr  (log_plugin/to_zap_log_plugin.go:131)
(mindreader-node) WARN [11-26|15:17:46.583] The flag --rpcport is deprecated and will be removed June 2021, please use --http.port  (log_plugin/to_zap_log_plugin.go:131)
(mindreader-node) WARN [11-26|15:17:46.583] The flag --rpcapi is deprecated and will be removed June 2021, please use --http.api  (log_plugin/to_zap_log_plugin.go:131)
(mindreader-node) WARN [11-26|15:17:46.583] The flag --rpcvhosts is deprecated and will be removed June 2021, please use --http.vhosts  (log_plugin/to_zap_log_plugin.go:131)
(mindreader-node) WARN [11-26|15:17:46.583] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable  (log_plugin/to_zap_log_plugin.go:131)
```

**Comment by matthewdarwin** [comment]
If you use the latest geth-dm, then geth won't start as it doesn't recognize the options

**Comment by maoueh** [comment]
Already landed in `develop` a few weeks ago via 4065b9b6f63bfb7cc246fc2f3bed40671bd94f03

**Comment by matthewdarwin** [comment]
Does it need some configuration parameter?  I compiled today and got the old options.

Per the readme, this is the instructions I followed:

```
git clone https://github.com/streamingfast/sf-ethereum.git
cd sf-ethereum
go install ./cmd/sfeth 
```

**Comment by maoueh** [comment]
If it's still a problem, it's pretty weird, I just did a search for `rpc` in the codebase and found nothing that was related to flags .

Would you have logs around that?

**Comment by matthewdarwin** [comment]
Must be operator error.  Seems ok now.  Sorry about that.

During testing I must have upgraded geth first which gave the command line mismatch. Then hard-coded the command line in the config file.  I removed the hard-coded command line now and it is good.

Now let me try with bsc...

**Comment by maoueh** [comment]
All good, old versions of Geth since something like 1.9.25 have the support for the new flags, so we should be all good.
